---
title: "HBN Sample Selection"
author: "Audrey Luo"
output:
  html_document:
    code_folding: show
    highlight: haddock
    theme: lumen
    toc: yes
    toc_depth: 4
    toc_float: yes
---

 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(purrr)
library(stringr)
```

# Initial Participant List
```{r}
#list of RBC ids with processed, non-variant diffusion MRI data, N = 2063
participants <- read.csv("/cbica/projects/luo_wm_dev/input/HBN/sample_selection_files/HBN_NonVariantDWI_participantlist.csv") # generated by /cbica/projects/luo_wm_dev/code/Generate_input/4_QC_scripts/HBN_identify_variants.ipynb

colnames(participants) <- c("sub") 

```

# Construct Final Sample
```{r}
demographics <- read.delim("/cbica/projects/luo_wm_dev/input/HBN/sample_selection_files/HBN_Demographics.tsv") # copied over from network_replication
demographics <- demographics %>% rename(sub=participant_id)
 
demographics <- demographics[demographics$sub %in% participants$sub,] #demographic, medical, and clinical information for just the N = 2063 participants with non-variant diffusion MRI data
```

## Health History Exclusion
```{r}
#no medical exclusion in HBN
participants.final <- demographics 
```

## Diffusion Acquisition Exclusion
```{r}
dwi.qc <- read.csv("/cbica/projects/luo_wm_dev/input/HBN/sample_selection_files/HBN_DWI_QCmetrics.csv") #diffusion scan acquisition parameters and quality metrics, generated by /cbica/projects/luo_wm_dev/code/Generate_input/4_QC_scripts/diffusion_qcmetrics.ipynb
dwi.qc <- dwi.qc %>% rename(sub=subject_id) %>% rename(site=session_id) # format site variable
dwi.qc$site <- gsub("ses-", "", dwi.qc$site)
demographics <- merge(demographics, dwi.qc[,c("sub", "site")], by='sub') # add site info to demographics
participants.final <- demographics 

dwi.qc <- dwi.qc[dwi.qc$sub %in% participants$sub,] # QC info for just the N = 2063 participants with non-variant diffusion data
```

```{r}
acquisitionexclude <- dwi.qc %>% filter(raw_num_directions != 129) %>% select(sub) #participants to exclude from the final study sample for missing a diffusion MRI run (none)

participants.final <- participants.final[!participants.final$sub %in% acquisitionexclude$sub,] %>% as.data.frame() #remove 0 participants from the sample, remaining N = 2063
```

## Diffusion Quality Exclusion
```{r}
qualityexclude <- dwi.qc %>% filter(t1_neighbor_corr < 0.6) %>% select(sub) #participants to exclude from the final study sample based on processed diffusion MRI neighborhood correlation


# participants to exclude based on manual QA: exclude T1 based on `tri.nary_score_without_rater.2`==0
# note that trinary score == 2 means good, == 0 means bad, == 1 means in between
T1_QA <- read.csv("/cbica/projects/luo_wm_dev/input/HBN/sample_selection_files/T1_QA_HBN_NathaliaEsper_20230630.csv")
T1_QA <- T1_QA %>% rename(sub=ID)
T1_QA <- T1_QA %>% mutate(t1Exclude = ifelse(tri.nary_score_without_rater.2 == 0, 1, 0))
qualityexclude <- rbind(qualityexclude, T1_QA %>% filter(t1Exclude==1) %>% select(sub))  

participants.final <- participants.final[!participants.final$sub %in% qualityexclude$sub,] %>% as.data.frame() #remove 92 participants from the sample of 2063 due to diffusion data quality, remaining N = 1971
```


```{r}

# tsv from https://fcp-indi.s3.amazonaws.com/index.html#data/Projects/HBN/BIDS_curated/derivatives/qsiprep/)
# exclude participants that had didn't have preprocessed, BIDS-compliant dMRI data (based on HBN-POD2 curation)
pod2 <- read.delim("/cbica/projects/luo_wm_dev/input/HBN/sample_selection_files/HBN-POD2.tsv")
pod2 <- pod2 %>% rename(sub=subject_id)
  
participants.final <- inner_join(participants.final, pod2[,c('sub', 'expert_qc_score', 'xgb_qsiprep_qc_score', 'xgb_qc_score', 'dl_qc_score')], by = "sub") # remove 24 participants from sample of 1971 due to not being BIDS-compliant dMRI data, remaining N = 1947

# exclude based on expert rater score and CNN-i +q score from HBN-POD2 (CNN-i score is the definitive QC score, according to Richie-Halford paper)
pod2exclude <- participants.final %>% filter(expert_qc_score < 0.6 | dl_qc_score < 0.6)


participants.final <- participants.final[!participants.final$sub %in% pod2exclude$sub,] %>% as.data.frame() # remove 624 participants from sample of 1947 due to failing expert rater, remaining N = 1323

```

## Diffusion Scan Head Motion Exclusion
```{r}
motionexclude <- dwi.qc %>% filter(mean_fd > 1) %>% select(sub) #participants to exclude from the final study sample based on high in-scanner head motion during the diffusion runs. (Note that 8 of these participants were already excluded in previous steps)
 
participants.final <- participants.final[!participants.final$sub %in% motionexclude$sub,] %>% as.data.frame()  #remove additional 46 participants from the sample of 1323 due to in-scanner head motion, remaining N = 1277
```

## Age Range Exclusion 
```{r}

participants.final <- participants.final[!participants.final$sub %in% demographics$sub[which(is.na(demographics$age))],] %>% as.data.frame()  #remove additional 1 participant from the sample of 1277 due to missing age data, remaining N = 1276
```

# Save Temp Sample: Subject List and Demographics
```{r}

# Make final sample demographics dataframe
demographics.final <- demographics[demographics$sub %in% participants.final$sub,] %>% select(sub, age, sex, race, site) # combine demographics data 
 
# Make final sample QC metrics dataframe 
dwi.qc.final <- dwi.qc[dwi.qc$sub %in% participants.final$sub,] %>% select(sub, mean_fd, t1_neighbor_corr) 
 
 
sub_id <- participants.final$sub %>% as.data.frame() %>% setNames("sub_id")

write.table(sub_id, "/cbica/projects/luo_wm_dev/input/HBN/sample_selection_files/HBN_WMDev_TempSample_N1276_age5to22.txt", col.names=T, row.names=F, quote = TRUE)
write.table(sub_id, "/cbica/projects/luo_wm_dev/input/HBN/subject_list/HBN_tempsubject_list.txt", col.names=F, row.names=F, quote = FALSE)
#write.table(sub_id[c(1:3),], "/cbica/projects/luo_wm_dev/input/HBN/subject_list/HBN_subject_list_test.txt", col.names=F, row.names=F, quote = FALSE)
write.csv(demographics.final, "/cbica/projects/luo_wm_dev/input/HBN/sample_selection_files/HBN_WMDev_TempSampleDemographics_N1276_age5to22.csv", quote = F, row.names = F)
write.csv(dwi.qc.final, "/cbica/projects/luo_wm_dev/input/HBN/sample_selection_files/HBN_WMDev_TempSampleQCMetrics_N1276_age5to22.csv", quote = F, row.names = F)

which(sub_id$V1 == "sub-NDARME656MTN")
```

## Missing Data Exclusion -- will need to update after running dki
```{r}
# load near-final lists
sub_id <- read.csv("/cbica/projects/luo_wm_dev/input/HBN/sample_selection_files/HBN_WMDev_TempSample_N1276_age5to22.txt")
demographics.temp <- read.csv("/cbica/projects/luo_wm_dev/input/HBN/sample_selection_files/HBN_WMDev_TempSampleDemographics_N1276_age5to22.csv")
dwi.qc.temp <- read.csv("/cbica/projects/luo_wm_dev/input/HBN/sample_selection_files/HBN_WMDev_TempSampleQCMetrics_N1276_age5to22.csv")

# subjects with missing data
missing_freesurfer <- c("sub-NDARMN302YAV", "sub-NDAREW661NZJ", "sub-NDARYZ489EHH", "sub-NDAREH074NG8", "sub-NDARRR622MYT", "sub-NDARTF133LLM", "sub-NDARNM147CG2", "sub-NDARFU444HEF", "sub-NDARCG785NND", "sub-NDARVM287DJK", "sub-NDARNE406XC3", "sub-NDARJX121GKP", "sub-NDARZV983XK9")

participants.final <- sub_id %>% setNames("sub")

participants.final <- participants.final$sub[!participants.final$sub %in% missing_freesurfer] %>% as.data.frame() #remove additional 13 participants from the sample of 1276 due to missing freesurfer data, remaining N = 1263
names(participants.final) <- "sub"

write.table(participants.final, "/cbica/projects/luo_wm_dev/input/HBN/subject_list/HBN_tempsubject_list_N1263.txt", col.names=F, row.names=F, quote = FALSE)
```


```{r}
failed_babs <- read.csv('/cbica/projects/luo_wm_dev/input/HBN/HBN_tractprofiles/all_subjects/failed_qsiprep_babs.csv', header=F)
failed_babs <- data.frame(c(c(failed_babs$V1), "sub-NDARWV470ATB")) %>% setNames("V1") # need to add this subject that took forever to run tractography and had to be terminated
missing_tracts <- read.csv("/cbica/projects/luo_wm_dev/input/HBN/HBN_tractprofiles/all_subjects/subjects_with_missing_tracts.csv")

# remove participants that failed babs/qsiprep 
participants.final <- sub_id[!sub_id$sub_id %in% failed_babs$V1,] %>% as.data.frame() #remove 28 participants that failed babs and qsiprep, remaining N = 1247
names(participants.final) <- "sub"

# remove participants that had missing tracts after pyafq (fyi, I'm seeing large age distribution of participants missing tracts)
participants.final <- participants.final[!participants.final$sub %in% missing_tracts$subjectID,] %>% as.data.frame() #remove 31 participants that are missing tracts are pyAFQ, remaining N = 1216
names(participants.final) <- "sub"

# in summary: 59 participants were removed for missing data, remaining N=1216
 
```

# Final sample
```{r}

# Make final sample demographics dataframe
demographics.final <- demographics.final[demographics.final$sub %in% participants.final$sub,]  # combine demographics data 
 
# Make final sample QC metrics dataframe 
dwi.qc.final <- dwi.qc.final[dwi.qc.final$sub %in% participants.final$sub,]  

sub_id <- participants.final$sub %>% as.data.frame() %>% setNames("sub_id")

write.table(sub_id, "/cbica/projects/luo_wm_dev/input/HBN/sample_selection_files/HBN_WMDev_FinalSample_N1216_age5to22.txt", col.names=T, row.names=F, quote = TRUE)
write.csv(demographics.final, "/cbica/projects/luo_wm_dev/input/HBN/sample_selection_files/HBN_WMDev_FinalSampleDemographics_N1216_age5to22.csv", quote = F, row.names = F)
write.csv(dwi.qc.final, "/cbica/projects/luo_wm_dev/input/HBN/sample_selection_files/HBN_WMDev_FinalSampleQCMetrics_N1216_age5to22.csv", quote = F, row.names = F)

```


```{r}
demographics <- read.csv("/cbica/projects/luo_wm_dev/input/HBN/sample_selection_files/HBN_WMDev_FinalSampleDemographics_N1216_age5to22.csv")
# sub-NDARZZ810LVF

demographics
demographics[which(demographics$sub == "sub-NDARZZ810LVF"),]

demographics[which(demographics$site == "HBNsiteSI"),]

# sub-NDARAC331VEH

```

