---
title: "HCPD Final Sample Selection"
author: "Audrey Luo"
output:
  html_document:
    code_folding: show
    highlight: haddock
    theme: lumen
    toc: yes
    toc_depth: 4
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(purrr)
library(stringr)
```

# Initial Participant List
```{r}
#list of RBC ids with processed, non-variant diffusion MRI data, N = 639  
participants <- read.csv("/cbica/projects/luo_wm_dev/input/HCPD/sample_selection_files/HCPD_NonVariantDWI_participantlist.csv") # generated by /cbica/projects/luo_wm_dev/code/Generate_input/4_QC_scripts/HCPD_IdentifyVariants.ipynb

colnames(participants) <- c("rbcid") 
```

# Construct Final Sample
```{r}
demographics <- read.csv("/cbica/projects/luo_wm_dev/input/HCPD/sample_selection_files/hcpd_demographics.csv") # originally downloaded from /cbica/projects/RBC/Curation/RBC_demo_pheno/data/hcpd_demographics.csv but this file has since been moved. Also available on PennLINC slack.
demographics$rbcid <- gsub("HCD", "sub-", demographics$src_subject_id) 
demographics <- demographics[demographics$rbcid %in% participants$rbcid,] #demographic, medical, and clinical information for just the N = 639 participants with non-variant diffusion MRI data
```

## Health History Exclusion
```{r}
# medhis_2e = cancer/leukemia
# medhis_2p = sickle cell anemia
# ms = multiple sclerosis
# ph_9 = has had a seizure
# cfmh_chd_seizure = has been to the doctor for epilepsy
# cfmh_chd_cerpalsy = has been to the doctor for cerebral palsy
# medhis_6j = has been knocked unconscious

healthexclude <- demographics %>% filter(medhis_2e == 1 | medhis_2p == 1 | ms == 1 | ph_9 == 1 | cfmh_chd_seizure == 1 | cfmh_chd_cerpalsy == 1 | medhis_6j == 1) %>% select(rbcid) #participants to exclude from the final study sample for medical or health history

participants.final <- participants[!participants$rbcid %in% healthexclude$rbcid,] %>% as.data.frame() %>% setNames(c("rbcid")) #remove 7 health exclude participants from the initial sample of 639 individuals with non-variant diffusion MRI data, remaining N = 632
```

## Diffusion Acquisition Exclusion
```{r}
dwi.qc <- read.csv("/cbica/projects/luo_wm_dev/input/HCPD/sample_selection_files/HCPD_DWI_QCmetrics.csv") #diffusion scan acquisition parameters and quality metrics, generated by /cbica/projects/luo_wm_dev/code/Generate_input/4_QC_scripts/diffusion_qcmetrics.ipynb

dwi.qc <- dwi.qc[dwi.qc$subject_id %in% participants$rbcid,] # QC info for just the N=639 participants with non-variant diffusion data
```

```{r}
acquisitionexclude <- dwi.qc %>% filter(raw_num_directions != 398) %>% select(subject_id) #participants to exclude from the final study sample for missing a diffusion MRI run, resulting in 298 or 299 diffusion directions instead of 398

participants.final <- participants.final[!participants.final$rbcid %in% acquisitionexclude$subject_id,] %>% as.data.frame() %>% setNames(c("rbcid")) #remove 8 participants from the sample of 632 health include individuals due to missing gradient directions, remaining N = 624
```

## Diffusion Quality Exclusion
```{r}
qualityexclude <- dwi.qc %>% filter(t1_neighbor_corr < 0.6) %>% select(subject_id) #participants to exclude from the final study sample based on processed diffusion MRI neighborhood correlation

participants.final <- participants.final[!participants.final$rbcid %in% qualityexclude$subject_id,] %>% as.data.frame() %>% setNames(c("rbcid")) #remove 14 participants from the sample of 624 due to diffusion data quality, remaining N = 610
```

## Diffusion Scan Head Motion Exclusion
```{r}
motionexclude <- dwi.qc %>% filter(mean_fd > 1) %>% select(subject_id) #participants to exclude from the final study sample based on high in-scanner head motion during the diffusion runs. (Note that 6 of these participants were already excluded in previous steps)

participants.final <- participants.final[!participants.final$rbcid %in% motionexclude$subject_id,] %>% as.data.frame() %>% setNames(c("rbcid")) #remove 24 participants from the sample of 610 due to in-scanner head motion, remaining N = 586
```

## Age Range Exclusion 
```{r}
# Participants to exclude for being outside PNC age range
ageexclude <- demographics %>% filter(interview_age/12 < 8) %>% select(rbcid)

# Remove 14 participants from the sample of 586 due to young age, remaining N = 572
participants.final <- participants.final[!participants.final$rbcid %in% ageexclude$rbcid,] %>% as.data.frame() %>% setNames(c("sub"))
```

## Save Temporary Sample for PyAFQ: Subject List and Demographics
```{r}
# Make temp sample demographics dataframe
demographics.temp <- demographics[demographics$rbcid %in% participants.final$sub,] %>% select(rbcid, interview_age, sex, race, site) %>% mutate(interview_age = interview_age/12) %>% rename(sub = rbcid, age=interview_age) # combine demographics data 

# Make temp sample QC metrics dataframe 
dwi.qc.temp <- dwi.qc[dwi.qc$subject_id %in% participants.final$sub,] %>% select(subject_id, mean_fd, t1_neighbor_corr) %>% rename(sub = subject_id) # note that var(t1_neighbor_corr) = 0.001338567 and var(mean_fd) = 0.02042722
 
sub_id <- demographics.temp$sub %>% as.data.frame() %>% setNames("sub_id") # want the same ordering as demographics df

write.table(sub_id, "/cbica/projects/luo_wm_dev/input/HCPD/sample_selection_files/HCPD_WMDev_TempSample_N572_age8to22.txt", col.names=T, row.names=F, quote = TRUE)
#write.table(sub_id, "/cbica/projects/luo_wm_dev/input/HCPD/subject_list/HCPD_tempsubject_list.txt", col.names=F, row.names=F, quote = FALSE)
write.table(sub_id, "/cbica/projects/luo_wm_dev/input/HCPD/subject_list/HCPD_subject_list_babs.txt", col.names=T, row.names=F, quote = FALSE)
write.table(sub_id[c(1:3),], "/cbica/projects/luo_wm_dev/input/HCPD/subject_list/HCPD_subject_list_test.txt", col.names=F, row.names=F, quote = FALSE)
write.csv(demographics.temp, "/cbica/projects/luo_wm_dev/input/HCPD/sample_selection_files/HCPD_WMDev_TempSampleDemographics_N572_age8to22.csv", quote = F, row.names = F)
write.csv(dwi.qc.temp, "/cbica/projects/luo_wm_dev/input/HCPD/sample_selection_files/HCPD_WMDev_TempSampleQCMetrics_N572_age8to22.csv", quote = F, row.names = F)
```

## Missing Data Exclusion (after pyAFQ)
```{r}
# No subjects failed babs
# No subjects were missing tracts after pyAFQ. The two following txt files are blank
# subs_missing_tracts <- read.table("/cbica/projects/luo_wm_dev/input/HCPD/sample_selection_files/subs_missing_tracts.txt", header=T)
# subs_with_nans <- read.table("/cbica/projects/luo_wm_dev/input/HCPD/sample_selection_files/subs_with_nans.txt", header=T)
```

## Save Final Sample: Subject List, Demographics, QC measures
```{r}
write.table(sub_id, "/cbica/projects/luo_wm_dev/input/HCPD/subject_list/final_sample/HCPD_WMDev_FinalSample.txt", col.names=T, row.names=F, quote = TRUE)
write.csv(merge(demographics.temp, dwi.qc.temp), "/cbica/projects/luo_wm_dev/input/HCPD/sample_selection_files/final_sample/HCPD_WMDev_FinalSampleDemoQC.csv", quote = F, row.names = F)
```


```{r}
sub_id <- read.table("/cbica/projects/luo_wm_dev/input/HCPD/subject_list/final_sample/HCPD_WMDev_FinalSample.txt", header=T)

setdiff(sub_id$sub_id, unique(all_subjects$sub))
```

