---
title: "PNC Sample Selection"
author: "Audrey Luo"
output:
  html_document:
    code_folding: show
    highlight: haddock
    theme: lumen
    toc: yes
    toc_depth: 4
    toc_float: yes
---

 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(purrr)
library(stringr)
```

# Initial Participant List
```{r}
#list of RBC ids with processed, non-variant diffusion MRI data, N = 1368  
participants <- read.csv("/cbica/projects/luo_wm_dev/input/PNC/sample_selection_files/PNC_NonVariantDWI_participantlist.csv") # generated by /cbica/projects/luo_wm_dev/code/Generate_input/4_QC_scripts/PNC_identify_variants.ipynb

colnames(participants) <- c("sub") 

```

# Construct Final Sample
```{r}
demographics <- read.csv("/cbica/projects/luo_wm_dev/input/PNC/sample_selection_files/n1601_demographics_go1_20161212.csv") # copied over from network_replication
bblid_scanid <- read.csv("/cbica/projects/luo_wm_dev/input/PNC/sample_selection_files/bblid_scanid_sub.csv")
demographics <- merge(demographics, bblid_scanid, by ="scanid")
demographics <- demographics %>% relocate(bblid, rbcid)
demographics <- dplyr::rename(demographics, sub = rbcid) %>% mutate(age = ageAtScan1/12)
demographics$sub <- paste0("sub-", demographics$sub)
 
demographics <- demographics[demographics$sub %in% participants$sub,] #demographic, medical, and clinical information for just the N = 1368 participants with non-variant diffusion MRI data
```

## Health History Exclusion
```{r}
health_exclude_data <- read.csv("/cbica/projects/luo_wm_dev/input/PNC/sample_selection_files/n1601_health_20170421.csv")
healthexclude <- paste0("sub-", health_exclude_data$bblid[c(which(health_exclude_data$healthExcludev2==1))]) #fyi, bblid in health_exclude_data corresponds to sub in demographics 

participants.final <- demographics[-c(which(demographics$sub %in% healthexclude)),] #remove 118 health exclude participants from the initial sample of 1368 individuals with non-variant diffusion MRI data, remaining N = 1250
```

## Diffusion Acquisition Exclusion
```{r}
dwi.qc <- read.csv("/cbica/projects/luo_wm_dev/input/PNC/sample_selection_files/PNC_DWI_QCmetrics.csv") #diffusion scan acquisition parameters and quality metrics, generated by /cbica/projects/luo_wm_dev/code/Generate_input/4_QC_scripts/diffusion_qcmetrics.ipynb

dwi.qc <- dwi.qc[dwi.qc$subject_id %in% participants$sub,] # QC info for just the N=1368 participants with non-variant diffusion data
```

```{r}
acquisitionexclude <- dwi.qc %>% filter(raw_num_directions != 71) %>% select(subject_id) #participants to exclude from the final study sample for missing a diffusion MRI run, resulting in 35 diffusion directions instead of 71
 
participants.final <- participants.final[!participants.final$sub %in% acquisitionexclude$subject_id,] %>% as.data.frame() #remove 10 participants from the sample of 1250 health include individuals due to missing gradient directions, remaining N = 1240
```

## Diffusion Quality Exclusion
```{r}
#participants to exclude from the final study sample based on processed diffusion MRI neighborhood correlation
qualityexclude <- dwi.qc %>% filter(t1_neighbor_corr < 0.6) %>% select(subject_id) 

# participants to exclude based on manual QA
T1_QA <- read.csv("/cbica/projects/luo_wm_dev/input/PNC/sample_selection_files/n1601_t1QaData_20170306.csv")
T1_QA <- merge(T1_QA, bblid_scanid, by ="scanid")
T1_QA <- dplyr::select(T1_QA, -bblid.y)
T1_QA <- T1_QA %>% relocate(rbcid) 
T1_QA <- T1_QA %>% dplyr::rename(sub=rbcid)
T1_QA$sub <- paste0("sub-", T1_QA$sub)

qualityexclude <- rbind(qualityexclude, T1_QA %>% filter(t1Exclude==1) %>% select(sub) %>% rename(subject_id=sub))

participants.final <- participants.final[!participants.final$sub %in% qualityexclude$subject_id,] %>% as.data.frame() #remove an additional 26 participants from the sample of 1240 due to diffusion data quality, remaining N = 1214
```

## Diffusion Scan Head Motion Exclusion
```{r}
motionexclude <- dwi.qc %>% filter(mean_fd > 1) %>% select(subject_id) #participants to exclude from the final study sample based on high in-scanner head motion during the diffusion runs.  
 
participants.final <- participants.final[!participants.final$sub %in% motionexclude$subject_id,] %>% as.data.frame()  #remove additional 61 participants from the sample of 1214 due to in-scanner head motion, remaining N = 1153
```


## Age Range Exclusion 
```{r}
# not doing age range exclusion for PNC 

```

 

## Save Temporary Sample for PyAFQ: Subject List and Demographics
```{r}

# Make temp sample demographics dataframe
demographics.temp <- demographics[demographics$sub %in% participants.final$sub,] %>% mutate(age = ageAtScan1/12) %>% select(sub, age, sex, race)# combine demographics data 

# Make temp sample QC metrics dataframe 
dwi.qc.temp <- dwi.qc[dwi.qc$subject_id %in% participants.final$sub,] %>% select(subject_id, mean_fd, t1_neighbor_corr) %>% rename(sub = subject_id) # note that var(t1_neighbor_corr) = 0.0001081781 and var(mean_fd) = 0.0237685
 
sub_id <- demographics.temp$sub %>% as.data.frame() %>% setNames("sub_id") # want the same ordering as demographics df
write.table(sub_id, "/cbica/projects/luo_wm_dev/input/PNC/subject_list/PNC_tempsubject_list.txt", col.names=F, row.names=F, quote = FALSE)
write.table(sub_id, "/cbica/projects/luo_wm_dev/input/PNC/subject_list/PNC_subject_list_babs.txt", col.names=T, row.names=F, quote = FALSE)
#write.table(sub_id[c(1:3),], "/cbica/projects/luo_wm_dev/input/PNC/subject_list/PNC_subject_list_test.txt", col.names=F, row.names=F, quote = FALSE)
 
write.csv(demographics.temp, "/cbica/projects/luo_wm_dev/input/PNC/sample_selection_files/PNC_WMDev_TempSampleDemographics_N1153_age8to23.csv", quote = F, row.names = F)
write.csv(dwi.qc.temp, "/cbica/projects/luo_wm_dev/input/PNC/sample_selection_files/PNC_WMDev_TempSampleQCMetrics_N1153_age8to23.csv", quote = F, row.names = F)


```



# Save Final Sample: Subject List and Demographics
```{r}

# Make final sample demographics dataframe
demographics.final <- demographics[demographics$sub %in% participants.final$sub,] %>% select(sub, age, sex, race) # combine demographics data 

# Make final sample QC metrics dataframe 
dwi.qc.final <- dwi.qc[dwi.qc$subject_id %in% participants.final$sub,] %>% select(subject_id, mean_fd, t1_neighbor_corr) %>% rename(sub = subject_id)  
 

sub_id <- as.data.frame(participants.final$sub)  %>% setNames("sub_id")
write.table(sub_id, "/cbica/projects/luo_wm_dev/input/PNC/sample_selection_files/PNC_WMDev_FinalSample_N1153_age8to22.txt", col.names=T, row.names=F, quote = TRUE)
write.csv(demographics.final, "/cbica/projects/luo_wm_dev/input/PNC/sample_selection_files/PNC_WMDev_FinalSampleDemographics_N1153_age8to22.csv", quote = F, row.names = F)
write.csv(dwi.qc.final, "/cbica/projects/luo_wm_dev/input/PNC/sample_selection_files/PNC_WMDev_FinalSampleQCMetrics_N1153_age8to22.csv", quote = F, row.names = F)

```

 
